#!/usr/bin/python3

from plano import *

save_dir = make_temp_dir()

notice("Saving any existing files to {}", save_dir)

def install_link(source_file, target_file=None):
    assert source_file is not None
    
    if target_file is None:
        target_file = source_file
    
    source_file = absolute_path(source_file)

    if not is_absolute(target_file):
        target_file = join(home_dir(), target_file)
    
    if exists(target_file):
        move(target_file, save_dir)

    make_link(source_file, target_file)

install_link(".bashrc")
install_link(".config/ghost/config.py")
install_link(".emacs")
install_link(".emacs.d/doc-mode.el")
install_link(".gitconfig")
install_link(".terminfo/d/dumb-emacs-ansi")
